[tox]
envlist = py312, py313
runner = uv-venv-lock-runner

[gh-actions]
python =
    3.12: py312
    3.13: py313

[testenv]
dependency_groups = dev
commands =
    pytest --cov --cov-config=pyproject.toml --cov-report=xml tests
    pyright
